### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bolam-o** [dance-with-rb/client#2]
- [ ] 카카오 맵 API 연동부 코드 개선
- [ ] 맵이 나오기까지의 로드 시간 개선
- [ ] 서비스 이용전 HTML Geolocation api 위치 조회 권한 허용 장려 모달 생성 필요
  - 이후 권한 미허용 시에 대한 최초 마커 생성 위치, 날씨, 미세먼지 데이터 사전 정의 필요.
- [ ] 사용자 현재 위치 조회 및 현재 위치 마커 생성
- [ ] 날씨와 미세먼지 알림 박스 
- [ ] 생성된 마크 hover 시 대여소 명 노출, click 시 해당 대여소의 정보를 포함하는 모달 생성

**Comment by bolam-o** [comment]
`projects` 탭 이관 완료
